### ISSUE TITLE
@je

### ISSUE THREAD

**Issue by DFillmore** [DFillmore/Z-Machine-Standard#10]
je can take between 2 and 4 operands. je with just 1 operand is not
permitted.

**Comment by fredrikr** [comment]
Standard 1.1 already states that giving just 1 operand is not permitted, but at the same time it says that "@je a" never branches.

**Comment by crawlingChaos** [comment]
Infocom's own interpreters disagree on behavior here.  Some branch with zero or one operand, some do not.
