### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by DFillmore** [DFillmore/Z-Machine-Standard#2]
The standard currently states that story file padding beyond the length
specified in the header must be all zero bytes. Many Infocom story files in
fact contain non-zero data in the padding, so interpreters must be sure to
exclude the padding from checksum calculations.

**Comment by crawlingChaos** [comment]
There is one annoying exception to this:
A Mind Forever Voyaging [84.850516] FullAlpha.z4
This file contains non-zero padding which unfortunately **is** included in the checksum, or more likely, the file length value is smaller than it should be.
