### ISSUE TITLE
@get_cursor lower window 

### ISSUE THREAD

**Issue by curiousdannii** [DFillmore/Z-Machine-Standard#43]
From https://intfiction.org/t/cursor-position-in-z-code/41400

Spec could be clearer in both chapters 8 and 15 that @get_cursor will only return the cursor of the upper window.

**Comment by DFillmore** [comment]
Currently in section 8 we have:
8.7.2.3
When the upper window is selected, its cursor position can be moved with set_cursor. This position is given in characters in the form (row, column), with (1,1) at the top left. The opcode has no effect when the lower window is selected. It is illegal to move the cursor outside the current size of the upper window.

I propose rewriting this as:

8.7.2.3
The position of the cursor in the upper window can be set and retrieved with set_cursor and get_cursor.

8.7.2.3.1
When the upper window is selected, its cursor position can be moved with set_cursor. This position is given in characters in the form (row, column), with (1,1) at the top left. 
The opcode has no effect when the lower window is selected. It is illegal to move the cursor outside the current size of the upper window.

8.7.2.3.2
When either the upper or lower windows are selected, get_cursor returns the position of the cursor in the upper window.

**Comment by DFillmore** [comment]
I've also rewritten set_cursor and get_cursor in section 15, as well as clarifying in various places that positions are in units, not characters.
