### ISSUE TITLE
Stop recommending setting height to 255?

### ISSUE THREAD

**Issue by curiousdannii** [DFillmore/Z-Machine-Standard#44]
https://intfiction.org/t/z-machine-1-0-update/6396/50

https://github.com/curiousdannii/ifvms.js/issues/56
https://github.com/curiousdannii/parchment/issues/48

>8.4.1
>The interpreter should use the screen height for calculating when to pause and print "[MORE]". A screen height of 255 lines means "infinite height", in which case the interpreter should never stop printing for a "[MORE]" prompt. (In case, say, the screen is actually a teletype printer, or has very good "scrollback".)

> Sec 11
> 20 | 4 |   | * | * | Screen height (lines): 255 means "infinite"

Several games use this header value to print full pages of blank lines. Should this be an anti pattern? Which terps actually set 255?

Games include Bureaucracy, Christminster, Theatre. For Bureaucracy at least, you can't just scroll down and have it work. (Though it could be another unrelated bug in Parchment, not sure.)

(Parchment/ZVM links will display it now, and I probably won't get to fixing it immediately.)
https://iplayif.com/?story=https://eblong.com/infocom/gamefiles/bureaucracy-r160-s880521.z4
https://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Ftheatre.z5
https://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fminster.z5

**Comment by DFillmore** [comment]
I'm going to have to investigate this one a bit. Planning to modify my terp and see how they run.

**Comment by DFillmore** [comment]
Yeah, okay, Bureaucracy breaks pretty badly, doesn't it? Not sure what to do about this one, as it's technically a bug in the game.

**Comment by DFillmore** [comment]
I'm more inclined to put a warning to interpreter writers that some games break if you try this, and a warning to game writers that they should really check for this special case.

**Comment by jpenney** [comment]
This does seem like a game bug in this case not checking for this case, and it sounds like it’s usually just annoying when it’s wrong outside of Bureaucracy (but maybe it’s also worth noting that specific problem).

**Comment by curiousdannii** [comment]
I'm not sure of the point of the recommendation. The interpreter can know not to print MORE without telling the game that its window is higher than it is.

**Comment by DFillmore** [comment]
I've no idea if there are any terps which set 255, but the problem here is, even if no terps use it, and no games pay attention to it, it's still not actually an error in the specification. Changes to the 1.0 (and 1.1) standards should not change expected behaviour, only correct mistakes and clear up ambiguities. If we think the 255 thing is a bad idea, we can add suggestions, but not just remove it. Maybe make a note and figure out a better way to indicate 'infinite screen height' to the game in a later version of the standard.

**Comment by curiousdannii** [comment]
IMO if the spec recommends something which *noone* does, and which has bad consequences, that is an error. How is something no one does the expect behaviour? Do we actually want every terp which provides good scrollback to change this header value? That's a lot, maybe most terps now.

**Comment by jpenney** [comment]
I didn’t take it as being recommended if you have good scroll-back. It’s saying you *could* use it in that case, but it’s really aimed at non-screen displays.  I can imagine it also being used to make it easier to use a screen reader.

**Comment by curiousdannii** [comment]
It just doesn't make much sense to me why if you were using a non-screen or teletype display why you'd want games to be printing 255 blank lines. Wouldn't you want less?

I think that the ifMud Floyd bot's Z-Machine uses cheapglk, which means it has a height of 24. What other non-screen terps are there?

**Comment by DFillmore** [comment]
If having 255 lines mean 'infinite height' is an error, it's an error in the design of the Z-Machine, not an error in the text of the Standard. If we want to change the design, we need a new standard version. 

I don't think the idea was to have games print 255 blank lines. 255 is supposed to be an indicator, not a literal line count.

**Comment by jpenney** [comment]
No one wants 255 blank lines. That’s a game bug. 255 is `$ff` the max 8-bit integer. There is no bigger number. It’s infinity, basically.

**Comment by DFillmore** [comment]
This was definitely a feature Infocom intended. I dont know if any of their terps or games made use of or paid attention to it.

**Comment by curiousdannii** [comment]
What exactly did Infocom do with it?

**Comment by curiousdannii** [comment]
Okay, what about this?

1. Return height 255 to its original meaning of a printing interpreter, not a terp with good scrollback.
2. Suggest/require that height 255 only be used in conjunction with turning off the screen splitting flag in Flags 1.
3. Rephrase 8.4.1 to something like
   >The interpreter is responsible for ensuring that the player can read more than one screen's worth of output between turns. It may accomplish this by displaying [MORE] after one complete screen and pausing for the player's input, or in a scrolling interpreter by printing all the text, and scrolling such that the player's last command is at the top of the screen.

**Comment by DFillmore** [comment]
I think we both want the same basic outcome here, which is to stop interpreter writers from using 255 as the screen height. I would like to also avoid altering the actual design from the original 1997 document.

My solution is to continue to document it more or less as it is, but strongly suggest no interpreter uses it, because it breaks games. Suggest instead to use some sensible height that's likely to work well for upper window shenanigans. If after this an interpreter writer uses 255 anyway, well, that's their choice.

**Comment by curiousdannii** [comment]
That's fair. You could make a remark saying something like Infocom intended it to be used to indicate printing/teletype interpreters, but that it's unclear how it would work in practice, and that their games don't seem to account for it.

**Comment by DFillmore** [comment]
8.4.1
The interpreter should use the screen height for calculating when to pause and print "[MORE]". In theory, a screen height of 255 lines means "infinite height" (in case, say, the screen is actually a teletype printer, or has very good "scrollback"), in which case the interpreter should never stop printing for a "[MORE]" prompt. However, interpreters should avoid setting the height to 255 in practice, as it can break some Inform and Infocom games.

**Comment by DFillmore** [comment]
And also just delete the 'infinite height' note in the header table.

**Comment by curiousdannii** [comment]
I'd think you should remove "or has very good "scrollback"" because that's not what the design was intended to be.

**Comment by DFillmore** [comment]
>8.4.1
>The interpreter should use the screen height for calculating when to pause and print "[MORE]".
>
>In theory, a screen height of 255 lines means "infinite height" (in case, say, the screen is actually a teletype printer), in which case the interpreter should never stop printing for a "[MORE]" prompt. In practice, however, interpreters should avoid setting the height to 255 as it causes serious problems with some Inform and Infocom games. Instead, the interpreter should simply pick a number for the >screen height based on a sensible maximum size for the upper window.

**Comment by curiousdannii** [comment]
Thanks, I think that's much clearer!

**Comment by DFillmore** [comment]
Slight problem that it says 'maximum size for upper window' but 8.4 is about version 6 as well, so I'm just reopening this to remind myself that needs fixing.

**Comment by DFillmore** [comment]
Changed the last sentence to 'Instead, the interpreter should simply pick a number for the screen height based on a sensible maximum size for screen operations such as split_window.'
