### ISSUE TITLE
@copy_table

### ISSUE THREAD

**Issue by fredrikr** [DFillmore/Z-Machine-Standard#45]
The standard says "If **size** is positive, the interpreter must copy either forwards or backwards so as to avoid corrupting **first** in the copying process."

If the tables, overlap, the whole table can't be copied without corrupting it. 

Does the standard mean that @copy_table should choose the direction that makes sure all the original contents of **first** are copied properly to **second** and accept that **first** is corrupted at the end of the copying process?

**Comment by DFillmore** [comment]
Yes. I assume this was supposed to mean 'avoid corrupting parts of **first** that have not yet been copied.

**Comment by curiousdannii** [comment]
I have a @copy_table test in Praxix, which I believe tests the intended behaviour.

**Comment by fredrikr** [comment]
Regardless, we should strive to make the standard as clear as possible.

PS @curiousdannii : Didn't know a new version of Praxix was out. Got the new version and found (and fixed) a bug in @scan_table!  in Ozmoo :). Thanks!

**Comment by DFillmore** [comment]
How about:
"The tables are allowed to overlap. If size is positive, the interpreter must copy either forwards or backwards so as to make sure all the original contents of first are copied to second, and avoid corrupting data in first that has not yet been copied. If size is negative, the interpreter must copy forwards even if this corrupts first. ('Beyond Zork' uses this to fill an array with spaces.)"
