### ISSUE TITLE
Description of @save

### ISSUE THREAD

**Issue by fredrikr** [DFillmore/Z-Machine-Standard#47]
The description of @save says it's a branch instruction in v4. However, the summary above the description says it's a store instruction in v4. The summary in section 14 says it's a store instruction too.

**Comment by DFillmore** [comment]
Fixed to remove all the bits that say V4 @save and @restore are store instructions.

**Comment by curiousdannii** [comment]
So I need to fix this in ZVM now. Does this mean that 0OP:181,182 don't have storing versions in V5+? The only proper opcodes are EXT:0,1?

**Comment by curiousdannii** [comment]
@taradinoc You'll need to update https://hansprestige.com/inform/zmachine_versions.html

**Comment by taradinoc** [comment]
Wait, what? According to the Frotz source, `@save` is a branch instruction until V3, and a store instruction in V4+:

https://github.com/DavidGriffith/frotz/blob/44fe81f567c79448320a111ba1d77365ac0509c2/src/common/fastmem.c#L987-L990

Have you tested this against the actual V4 games?

**Comment by taradinoc** [comment]
Infocom's assembly code for AMFV uses `SAVE` as a store instruction:

https://github.com/historicalsource/amfv/blob/master/verbs.zap#L156

**Comment by DFillmore** [comment]
Okay, I'll take another look at it. Infocom's EZIP documentation said it's a branch, and that's what I assumed in my terp.

**Comment by DFillmore** [comment]
I fixed it, again. Properly this time, I believe.
