### ISSUE TITLE
Make 11.1 (The format of the header) clearer

### ISSUE THREAD

**Issue by fredrikr** [DFillmore/Z-Machine-Standard#48]
There is no indication which values occupy one byte and which occupy two bytes. One can usually guess, but it's not always easy. I.e. Flags 1 could occupy two bytes, to make room for future additions.

Also, for two-byte flag fields, there is no description of which bit should be considered as bit 0. For a standard, this should be described in a way that leaves no doubt.

**Comment by DFillmore** [comment]
I think a significant cause of this is the decision to put some of the header contents into an appendix, because they're not important to interpreters. I'm not entirely comfortable deleting an entire appendix, at least until a later version of the standard. Maybe add the missing locations into the table, but just with links to the appendix?

**Comment by curiousdannii** [comment]
Having one page would be better I think, with it noting which parts are standardised, and which parts are convention. The appendix page is pretty short anyway, you could change it to just say "this appendix used to list the conventional parts of the header, which has now been merged into the [other page](https://www.inform-fiction.org/zmachine/standards/z1point1/sect11.html)".

**Comment by DFillmore** [comment]
I've added a 'Len' column. Let me know what you think.

**Comment by fredrikr** [comment]
Looks good, except Len is wrong for $1e, $1f, $20, $21.

**Comment by DFillmore** [comment]
I knew I was going to get it wrong somewhere in there. Thanks.

**Comment by DFillmore** [comment]
I've updated the header table in Appendix B in the same way. I'll have to give some thought to the wording on the two-byte flag field issue.

**Comment by DFillmore** [comment]
Added a note above the table in 11.1:

>Where Flags occupy two bytes, "Bit 0" refers to bit 0 of the second byte, "Bit 8" refers to bit 0 of the first byte.

**Comment by fredrikr** [comment]
Looks good to me.
