### ISSUE TITLE
@read_char

### ISSUE THREAD

**Issue by fredrikr** [DFillmore/Z-Machine-Standard#49]
The standard doesn't say whether the interpreter should display a cursor while @read_char is waiting for input. If the interpreter doesn't display a cursor, filling in the form at the beginning of Bureaucracy gets very difficult, since there's no way to tell where you are in the form.

The standard should probably say that the terp should show a cursor.

**Comment by curiousdannii** [comment]
This should only be a recommendation, not a requirement; it may not always be possible to show a cursor. Glk terps probably can't for example.

**Comment by DFillmore** [comment]
How about:
"If at all possible, interpreters should display a cursor at the current cursor position in the current window when @read or @read_char are waiting for input. While some interpreters may not be able to ensure a cursor is displayed, the lack of a cursor can be frustrating for the player in some games, e.g. Bureaucracy."

**Comment by fredrikr** [comment]
Sounds good.
