### ISSUE TITLE
Version 5 basic colour set for standard 1.1 

### ISSUE THREAD

**Issue by borg323** [DFillmore/Z-Machine-Standard#56]
The [1.1 proposal document](https://inform-fiction.org/zmachine/standards/ZSpec11-latest.txt) mentions:
```
Standard 1.1 interpreters must provide the following basic colour set,
regardless of machine type, in both Version 5 and Version 6:
```
...
```
 10 = light grey  (true $5AD6, $$0101101011010110)
 11 = medium grey (true $4631, $$0100011000110001)
 12 = dark grey   (true $2D6B, $$0010110101101011)
 13  reserved
 14  reserved
 15 = transparent (true -4) [V6 only]
```

However, section 8.3.1 of the 1.1 branch says: `Colours 10, 11, 12, 15 and -1 are available only in Version 6.`
I can't find any discussion on this change online, so my question is whether colours 10, 11 and 12 should be provided by conformant standard 1.1 interpreters for version 5 files.

**Comment by DFillmore** [comment]
The grey colours are V6 only. The table needs updating to reflect this.

**Comment by jpenney** [comment]
I thought that was an intentional change, but I might be misremembering.

**Comment by DFillmore** [comment]
Hmm, looking at the source document, it does look like an intentional change. I probably just missed it when updating the Standard. 

I'll edit 8.3.1 to allow the greys.

**Comment by jpenney** [comment]
In case it's of historical interest, I went though my Z-Machine mailing list archives and here's the basic summary of how this was arrived at.

The Amiga V6 model was "interesting" in that it had a hard color limit.  Changing the text color would change the already displayed text, not just text printed after the change.  Loading an image with different colors would remap images already on screen, etc. Making any updates to this model would be incompatible with Infocom's own v6 games.   The DOS model had gross fonts and low res, but those limitations were in the interpreter, not the game files.  Loading better images or adding true-color wasn't an incompatible change.

When I starting working with generating V6 game files (circa. 1999), I wanted to abstract it away, and I proposed this mess of header extension flags:

```
Hex	Contents
===	========
 0	Extension honored?
 1	Supports music?
 2	Multiple sound support?
 3	Full font style combination support?
 4	Supports 3-OP @set_colour?
 5	Provides Amiga text pallette?
 6	Each window has own colour pair?
 7	Supports multiple text colours?
```

This eventually morphed into the 1.1 proposal, which simplified it down to only supporting the Amiga mode for compatibility with existing Infocom game files (which they did by querying the interpreter number).

In April 2002 David Kinder worked out the correct gamma adjusted values that now appear in the spec by using his old Amiga and comparing it to a PC. I can't find the discussion about changing the V5 behavior at the moment, but I thought the basic feeling was it was more work to support the old color set in v5 and the new one in v6 than it was worth.

**Comment by DFillmore** [comment]
Speaking of the Z-Machine mailing list, the ifarchive has archives of postings from March 1997 through August 2002, which I'm sure leaves out a couple of years towards the end, including some discussion of the 1.1 proposal. Have you got the missing stuff? Any way you could share it (if it doesn't take too much effort)?

**Comment by borg323** [comment]
> Any way you could share it (if it doesn't take too much effort)?

Having gone through all the publicly available posts in the ifarchive earlier this year, I would appreciate this.

**Comment by jpenney** [comment]
I’ll see what I can do. I have an archive that has a handful of corrupted messages, but should be in pretty good shape.

**Comment by cmatraki** [comment]
@jpenney 
> I’ll see what I can do. I have an archive that has a handful of corrupted messages, but should be in pretty good shape.

Have you been able to do anything about this?

**Comment by jpenney** [comment]
Sorry. Life got crazy, and it slipped my mind. Setting a reminder for myself to take a look tomorrow.
