### ISSUE TITLE
Unclear language in 3.5.3 and 3.5.5.1

### ISSUE THREAD

**Issue by publysher** [DFillmore/Z-Machine-Standard#60]
Section 3.5.3 mentions that A2/7 is a new-line. This refers to the newline in the ZSCII table (10), which outside of the spec is more commonly known as a carriage return (\r). 

Propose to make clear that A2/7 is interpreted as ZSCII value 10. 

Section 3.5.5.1 also mentions newline (same proposal) and escape for A2/7. This is _not_ the escape character mentioned in the ZSCII table (27), but an escape character like '\' in C-like language. 

Propose to make clear that A2/6 is not a valid ZSCII value and refer explicitly to 3.4

**Comment by DFillmore** [comment]
How's this?

>3.4
>Z-character 6 from A2 is a 'ZSCII escape' character. It means that the two subsequent Z-characters specify a ten-bit ZSCII character code: the next Z-character gives the top 5 bits and the one after the bottom 5.

>3.5.3
>In Versions 2 to 4, the alphabet table for converting Z-characters into ZSCII character codes is as follows:
>`Z-char 6789abcdef0123456789abcdef`
>`current   --------------------------`
>`  A0      abcdefghijklmnopqrstuvwxyz`
>`  A1      ABCDEFGHIJKLMNOPQRSTUVWXYZ`
>`  A2       ^0123456789.,!?_#'"/\-:()`
>`          --------------------------`
>For example, in alphabet A1 the Z-character 12 is translated as a capital G (ZSCII character code 71).
>
>Character 6 in A2 is printed as a space here, but it is a 'ZSCII escape' character, and not translated using the alphabet table: see S 3.4 above. Character 7 in A2, written here as a circumflex ^, is a new-line (ZSCII 13).

>3.5.5.1
>Such an alphabet table consists of 78 bytes arranged as 3 blocks of 26 ZSCII values, translating Z->characters 6 to 31 for alphabets A0, A1 and A2. Z-characters 6 and 7 of A2, however, are still translated >as ZSCII escape and new-line (ZSCII 13) codes (as above).
