### ISSUE TITLE
Where can I find the latest version in an online readable format?

### ISSUE THREAD

**Issue by publysher** [DFillmore/Z-Machine-Standard#61]
Yes, HTML in itself is perfectly readable, but it would be nice if there was a published version as well, maybe using Github pages?

**Comment by DFillmore** [comment]
Yeah, this is a bit of a problem. Ideally, they'll go up on the inform 6 website to replace the ones already there, but I'm not going to push for that until I'm happy the changes have stopped, or at least slowed down enough to appear stopped.

An online version elsewhere that matches the latest repository commits is something I'd like as well. It doesn't look like Github pages will work with this repository, as it expects a 'master' branch. Even if I renamed the branches, I'd want both the 1.0 and 1.1 branches online, which doesn't look possible.

I'll try to put something together soon.

**Comment by curiousdannii** [comment]
Maybe it would be better to have 1.0 and 1.1 as folders in one branch? Then when changes are made to both it could be done in one commit too.

**Comment by DFillmore** [comment]
For now, at least, I have made these available at http://frobnitz.co.uk/zmachine/ along with my other Z-Machine spec related projects.
