### ISSUE TITLE
Section 8.7.1.3 is in the wrong place.

### ISSUE THREAD

**Issue by DFillmore** [DFillmore/Z-Machine-Standard#63]
The paragraph marked 8.7.1.3 is about the V6 screen model, but it is placed in the section for the V4/V5 screen model.

**Comment by curiousdannii** [comment]
8.3.5 is also V6 only, but doesn't say so and could be a little confusing.

**Comment by DFillmore** [comment]
Looks like I'd already fixed this one at some point. Must have been looking at an old version of the spec.
