### ISSUE TITLE
@set_colour and buffering

### ISSUE THREAD

**Issue by borg323** [DFillmore/Z-Machine-Standard#67]
According to the description for `@set_colour`, "...set text to be foreground-against-background. (Flush any buffered text to screen, in the old colours, first.)"

Some tests I did with an old Infocom interpreter hint that colour changes were recorded in the text buffer. Specifically, lines with many colour changes were wrapping earlier than lines with constant colour.

**Comment by DFillmore** [comment]
It sounds like storing the colour changes in the text buffer messed up the line wrapping? Not sure that's a thing we want to standardise. It's probably fine if interpreters don't literally flush the buffer whenever the spec says to, as long as this doesn't cause other problems (like making lines wrap weirdly).

**Comment by borg323** [comment]
I found this in the XZIP specification:
>The  CURSET,  SCREEN,  ERASE,  CLEAR  and  COLOR opcodes  output  any  buffered  text  to  the  screen  before  performing  any  other  action.   Any future opcodes defined which may change screen appearance will also be defined to output buffered text as their first action.

>Depending on how SPLIT, CURGET, DIROUT, FONT and HLIGHT are implemented in a particular interpreter, they may also want to output buffered text.  In some implementations, they will not need to, as for example HLIGHT in ZIP20 is implemented by placing hlighting characters in the output stream.  In an interpreter where HLIGHT is done by a system call (one meaning ”future output is underlined,”) it should output the buffer first.

The spec seems consistent with this as is.
